### ISSUE TITLE
Running analysis with multiple samples?

### ISSUE THREAD

**Issue by pawelqs** [wwylab/CliP#1]
Hi!
From the included examples I understand how to run CliP on each sample independently. Can CliP identify clones in multiple samples from the same tumor, eg. from diagnosis and relapse?
Regards,
Paweł

**Comment by kaixiany** [comment]
My apology for this very out dated response. Currently CliP only runs for single sample. For multiple samples, we have a pipeline that runs CliP individually for each sample, then run CSR (https://github.com/wwylab/CSR) to combine the results.
