### ISSUE TITLE
All mutations were excluded in preprocessing

### ISSUE THREAD

**Issue by hfl112** [wwylab/CliP#10]
Hi developers,
I've been running CliP successfully,  but I found few samples fail to pass the preprocessing step and got an error like "The empirical CP is off the chart, which may be caused by incorrect copy number or existence of super cluster". I found in the R code "`clonal.ind <- which(phi > 1.5)`" were identified as excluded mutations , so this phi means CCF estimated? Just want to know why does this happen? 
Thank you,
fn

**Comment by kaixiany** [comment]
This phi is cellular prevalence (CCF * purity). It is rare that all mutations were excluded, but we have observed some cases, especially in melanoma samples where the copy number status are typically complicated. 

So far it is still quite challenging to distinguish the cause of empirical CP going too large; thus, my suggestion is to try multiple samples to see if excluding all mutations constantly happens.

Please let us know any further concerns.

**Comment by yujie-jiang** [comment]
Hello,

Thank you for your interest in CliP~ For your question, if you see message like "The empirical CP is off the chart, which may be caused by incorrect copy number or existence of super cluster”, it is not really an error because CliP drops fishy SNVs based on different reasons in preprocessing. The phi you showed here is the empirical CP (cellular prevalence) value, and if you see a very large CP, it could be caused by inaccurate copy number/purity estimation, or some reason that we don’t know at this point.

We just fixed a small error that could cause wrong output in the excluded_SNVs.txt file, so you can rerun the preprocessing if needed. It is very rare to see all mutations being excluded, but you can check the excluded_SNVs.txt file for listed reasons.

Hope this helps~

Best,
Yujie

**Comment by hfl112** [comment]
Hi,
For my 2 problematic cases, I rerun clip after correcting the code as Yujie said, and I just noticed they got  different errors:
Case1:
```
Running preprocessing...
Preprocessing finished.
Running the main CliP function...
/home/hef/Tools/CliP-master/src/run_kernel_nosub.py:46: UserWarning: genfromtxt: Empty input file: "/home/hef/Tools/CliP-master/test/preprocess_result/r.txt"
  r = genfromtxt(prefix+"r.txt", delimiter="\t")
/home/hef/Tools/CliP-master/src/run_kernel_nosub.py:47: UserWarning: genfromtxt: Empty input file: "/home/hef/Tools/CliP-master/test/preprocess_result/n.txt"
  n = genfromtxt(prefix+"n.txt", delimiter="\t")
/home/hef/Tools/CliP-master/src/run_kernel_nosub.py:48: UserWarning: genfromtxt: Empty input file: "/home/hef/Tools/CliP-master/test/preprocess_result/minor.txt"
  minor = genfromtxt(prefix+"minor.txt", delimiter="\t")
/home/hef/Tools/CliP-master/src/run_kernel_nosub.py:49: UserWarning: genfromtxt: Empty input file: "/home/hef/Tools/CliP-master/test/preprocess_result/total.txt"
  total = genfromtxt(prefix+"total.txt", delimiter="\t")
/home/hef/Tools/CliP-master/src/run_kernel_nosub.py:51: UserWarning: genfromtxt: Empty input file: "/home/hef/Tools/CliP-master/test/preprocess_result/coef.txt"
  coef = genfromtxt(prefix+"coef.txt", delimiter="\t")
/home/hef/Tools/CliP-master/src/run_kernel_nosub.py:52: UserWarning: genfromtxt: Empty input file: "/home/hef/Tools/CliP-master/test/preprocess_result/cutbeta.txt"
  phicut = genfromtxt(prefix+"cutbeta.txt", delimiter=" ")
Elapsed time: 0.01sec

Error: No results found at the given location: /home/hef/Tools/CliP-master/test/preliminary_result
```
It looks like for this case, all mutations have been excluded. But if I compare the excluded_SNVs.txt or outPosition.txt to the original input snv, I found not all mutations are excluded.

Case 2:
```
Running preprocessing...
Preprocessing finished.
Running the main CliP function...
Exception in thread Running the main CliP function:
Traceback (most recent call last):
  File "/home/hef/Tools/miniconda3/envs/pyclone/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/hef/Tools/miniconda3/envs/pyclone/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hef/Tools/CliP-master/src/run_kernel_nosub.py", line 54, in run_clip_nosub
    No_mutation = len(r)
TypeError: len() of unsized object


Elapsed time: 0.00sec

Error: No results found at the given location: /home/hef/Tools/CliP-master/test/preliminary_result
Execution halted
```
For this case, I do have one mutation after proprocessing, but it still got an error

By the way, these two cases are actually from the same patient, and they indeed have a very complicated copy number status when we trying to finalize the purity and absolute CN. I think it's more related to this inaccurate CNV estimation or the complexity of this patient itself.
Hope this information might be helpful,
FN

**Comment by yujie-jiang** [comment]
Hello,

Case 1 is a very interesting question. Based on the logic of our preprocessing, excluded SNVs and SNVs we feed into main CliP function should be mutually exclusive, so I am surprised that you see case like this (Btw, you may have noticed that outPosition.txt includes a list of SNVs that belong to a specific category of our excluded SNVs).

For case 2, it might be errors during multi-processing. We are now switching from python threading to OpenMP (and we have a few other small changes), which may avoid the issue you encountered. The updated version will be online in a few days, and then you can try it again.

Hope this helps~

Best,
Yujie

**Comment by jiyunmaths** [comment]
@hfl112 We just updated CliP. Please rerun it with your data. Let us know if you have any problems. 
Thanks.

**Comment by hfl112** [comment]
> @hfl112 We just updated CliP. Please rerun it with your data. Let us know if you have any problems. Thanks.

Thank you. it's working, but for those problematic cases, still got a similar error. I think for those cases is more or less due to the inaccurate purity estimation or absoluteCN estimation
