### ISSUE TITLE
genomic regions that were suspected to present subclonal CNAs were filtered out

### ISSUE THREAD

**Issue by YingYa** [wwylab/CliP#11]
Hi,

According your manuscript, 'In the PCAWG study ([The ICGC/TCGA Pan-Cancer Analysis of Whole Genomes Consortium 2020](https://www.biorxiv.org/content/10.1101/2021.03.31.437383v1.full#ref-37)), genomic regions that were suspected to present subclonal CNAs were filtered out from the final CNA call set, which were then used for subclonal reconstruction. Similar considerations were taken in the TCGA study.', subclonal CNAs should be filtered out before running CliP?

Could I use all the segments?

Another questions: should the major_cn, minor_cn and total_cn be rounded to integer?

Thanks

**Comment by yujie-jiang** [comment]
Hello YingYa,

Thank you for your interest in CliP. Actually the sentence you quoted will be taken out in the latest version and our current output has not accounted for that possibility. Subclonal CNAs are not considered but is on our radar and might be included in future.

For your second question: Yes, major_cn and minor_cn need to be rounded to integer, and total_cn is basically the sum of major_cn and minor_cn. Hope this helps~

Best,
Yujie
