### ISSUE TITLE
input format

### ISSUE THREAD

**Issue by kgaonkar6** [wwylab/CliP#2]
Hello,

I've tried to run the sample input files and seems to work just fine. I then tried to run preprocess.R with my data which has 281 consensus snvs and 193 consensus cnv and then run_CliP.py with the processed data like `python3 run_CliP.py Output_dir/ path_to_output CliP.py 0.2`
to get 
253 rows in lam0.2_label.txt
253 rows in lam0.2_phi.txt

lam0.2_summary_table.txt
X1 | X2 | X3
--- | --- | ---
0 |  197  | 0.667
1 |  56   |  0.892

I'm not sure if the inputs for snv and cnv need to be overlapping regions , can you provide me some instructions on how to generate the required inputs? 

The outputs here seems to be 253 regions which is not equivalent to the number of cnvs nor snvs. Can you please provide some description on how to interpret the output?

Thanks!
Krutika

**Comment by pawelqs** [comment]
Some time ago I wanted to try out CliP and I found that 'preprocess.R' script silently drops some mutations without informing the user which of them are kept. Some mutations might be dropped each time when they are subsetting the data 
`some_data <- some_data[valid.ind]`
I am afraid that this algorithm is not actively developed. If you want to work with it you can modify the script to return the indices of kept mutations (for e.g. to create a list of all mutations and subset it in the same way as other data vectors are).

Best,
Pawel

**Comment by kaixiany** [comment]
CliP drops some SNVs while doing preprocessing. Some SNVs got dropped  due to incorrect copy number, over-estimated empirical cellular prevalence, etc. I will create a note to modify the preprocess script to output the list of dropped SNVs with reasons.

**Comment by kaixiany** [comment]
I have just updated the preprocess script to implement recording of the dropped SNVs and why it did so. I guess this issue can be closed now.

**Comment by pawelqs** [comment]
@kaixiany, your updates are not in the master branch, which users usually download
