### ISSUE TITLE
Issues with preprocess.R

### ISSUE THREAD

**Issue by KeyTals** [wwylab/CliP#5]
Hello,

I was trying to run CliP/preprocess.R  script with 3 input mentioned, but looks like it is looking for vcf file instead of 4 column snv text file also for cnv it is looking major and minor cnv with headers and doesnt work if you provide total cnv ? Even after this i am still running into error. Could you please inform me the correct input required to run  preprocess.R ?

Keyur

**Comment by yujie-jiang** [comment]
Hi Keyur,

Thank you very much for your feedback. We have updated the README and sample inputs, would you please re-download the whole package and try again to see if that solves the problem?

Currently the CNA input needs to have a total_cn column, so please be sure to have it. Furthermore, the SNV input needs to follow the sample's format (no new information required, just need to have t_alt_count and t_ref_count info in the 8th column). You can check out the updated README and see if that helps.

Please let me know if you have other questions.

Best,
Yujie
