### ISSUE TITLE
Error running new version

### ISSUE THREAD

**Issue by KeyTals** [wwylab/CliP#6]
Hello,

I am getting following error when i try to run v1.1 .

Running preprocessing...
Error in approximated.theta[[K]] :
  attempt to select less than one element in get1index
Calls: LinearApproximate ... plot.formula -> eval -> eval -> <Anonymous> -> eval -> eval
Execution halted

I am not able figure out what is wrong, i have uploaded my input here also.
[input.purity.clip.txt](https://github.com/wwylab/CliP/files/6359702/input.purity.clip.txt) 
[input.cnv.clip.txt](https://github.com/wwylab/CliP/files/6359710/input.cnv.clip.txt)
[input.snv.clip.txt](https://github.com/wwylab/CliP/files/6359712/input.snv.clip.txt)

Keyur

**Comment by yujie-jiang** [comment]
Hi Keyur,

I tested your dataset but I can get results without having any issue. The attached files are the results I get with
```python run_clip_main.py sample/input.snv.clip.txt sample/input.cnv.clip.txt sample/input.purity.clip.txt -b -n 10 -s 2000```, (you can always tune the -s and -n arguments for possibly more accurate result). Can you show me the command you use?

[final_result.zip](https://github.com/wwylab/CliP/files/6360128/final_result.zip)

By the way, for a large sample like this, we recommend using downsampling with a flag “-b”.

Best,
Yujie
